### ISSUE TITLE
A very big step while scrolling

### ISSUE THREAD

**Issue by Sigmanor** [hccampos/brackets-smooth-scroll#2]
A very big step while scrolling. Is there a solution how to reduce it?

![b](https://cloud.githubusercontent.com/assets/7986067/5654665/f264d696-96cd-11e4-9643-93210430d01e.gif)

**Comment by jlnwcic** [comment]
Great extension idea. Had to uninstall because of Sigmanor's reason.  Tried setting scroll on my Windows mouse 1 line, but oh my, how it scrooools.  Perhaps another iteration will address that.  Thanks though!
JL

**Comment by Sigmanor** [comment]
**jlnwcic,** you can try to change the value **var MAX_FORCE** in **Update main.js** file  https://github.com/Sigmanor/brackets-smooth-scroll/commit/ded5dba6a3835d6d01e81cc45b759308bcb6d9f6 and then step while scrolling will be smaller.

**Comment by jlnwcic** [comment]
That's the ticket!  For Windows, .3 seems to be the best balance.
Great extension!

**Comment by teflonranger** [comment]
.007

**Comment by janacm** [comment]
My ideal settings on windows 7 64 bit
    var STEP = 0.00000001;
    var FORCE_REDUCTION_FACTOR = 0.95;
    var PSEUDO_FRICTION = 0.95;
    var MAX_FORCE = 0.05;
    var SPEED_THRESHOLD = 0.001;

**Comment by hccampos** [comment]
@janacm Looks good. It would be nice to have some kind of options dialog or something. I am short on time currently and not even using brackets, but a PR would be great :)

**Comment by CubixSystem** [comment]
@janacm, on windows 8.1 64 bit
`var STEP = 0.00000001;` 
is ultra-slow.
Agree with @hccampos, we need gui
